name: deploy pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        uses: justgook/setup-elm@v1

      - name: Move files
        run: |
          mv ./concentration/src/ ./concentration/elm.json ./

      - name: Make
        run: elm make src/Main.elm

      - name: Rename files
        run: |
          mv ./index.html ./concentration.html

      - name: Remove files
        run: |
          rm -rf ./src elm.json ./elm-stuff

      - name: Move files
        run: |
          mv ./breakout/src/ ./breakout/elm.json ./

      - name: Make
        run: elm make src/Main.elm

      - name: Rename files
        run: |
          mv ./index.html ./breakout.html

      - name: Remove files
        run: |
          rm -rf ./src elm.json ./elm-stuff

      - name: Move files
        run: |
          mkdir ./public
          mv ./concentration.html ./breakout.html ./public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
